14:43:59 - ERR - ExecuteNonQuery - (ForeignKeyViolation('inserción o actualización en la tabla «users» viola la llave foránea «users_id_facultad_fkey»\nDETAIL:  La llave (id_facultad)=(0) no está presente en la tabla «faculties».\n'),)
14:44:24 - ERR - ExecuteNonQuery - (ForeignKeyViolation('inserción o actualización en la tabla «users» viola la llave foránea «users_id_carrera_fkey»\nDETAIL:  La llave (id_carrera)=(1) no está presente en la tabla «majors».\n'),)
14:52:55 - ERR - put - (KeyError('HTTP_TOKEN'),)
15:05:48 - ERR - ExecuteNonQuery - (InvalidTextRepresentation("la sintaxis de entrada no es válida para tipo integer: «guardiola»\nLINE 1: ...1, name = 'pep', lastname = 'pep' WHERE id_user = 'guardiola...\n                                                             ^\n"),)
15:06:45 - ERR - ExecuteNonQuery - (InvalidTextRepresentation("la sintaxis de entrada no es válida para tipo integer: «guardiola»\nLINE 1: ...1, name = 'pep', lastname = 'pep' WHERE id_user = 'guardiola...\n                                                             ^\n"),)
15:09:42 - ERR - ExecuteNonQuery - (InvalidTextRepresentation("la sintaxis de entrada no es válida para tipo integer: «guardiola»\nLINE 1: ...1, name = 'pep', lastname = 'pep' WHERE id_user = 'guardiola...\n                                                             ^\n"),)
15:16:11 - ERR - update_user - (TypeError("'bool' object is not subscriptable"),)
15:38:04 - ERR - delete - (TypeError('response_error() takes 1 positional argument but 2 were given'),)
15:41:20 - ERR - delete - (<BadRequest '400: Bad Request'>,)
15:42:01 - ERR - delete - (<BadRequest '400: Bad Request'>,)
15:42:44 - ERR - delete - (<BadRequest '400: Bad Request'>,)
15:43:40 - ERR - delete - (<BadRequest '400: Bad Request'>,)
16:42:01 - ERR - create_user - (TypeError("'bool' object is not subscriptable"),)
16:48:57 - ERR - update_user - (UnboundLocalError("cannot access local variable 'data' where it is not associated with a value"),)
16:48:57 - ERR - put - (UnboundLocalError("cannot access local variable 'result' where it is not associated with a value"),)
16:49:15 - ERR - update_user - (NameError("name 'data' is not defined"),)
16:49:15 - ERR - put - (UnboundLocalError("cannot access local variable 'result' where it is not associated with a value"),)
